### ISSUE TITLE
请问编译的target system该选啥？没看到有IPQ6000系列的选项呀，默认这个ATH79就行吗？

### ISSUE THREAD

**Issue by MmDawN** [King-Of-Knights/openwrt-6.x#1]
![image](https://github.com/King-Of-Knights/openwrt-6.x/assets/40926229/9b3bc135-56f5-40b2-a00f-cfea4ef50f51)

**Comment by King-Of-Knights** [comment]
Target System 选 Qualcomm Atheros 802.11ax WiSoC-s 看看
