### ISSUE TITLE
qihoo 360编译出错

### ISSUE THREAD

**Issue by xingpo5800** [King-Of-Knights/openwrt-6.x#10]
编译环境：ubuntu 22.04.1 内核5.4.0
build/genchecksum.o ../build-x86_64-pc-linux-gnu/libiberty/libiberty.a
echo "g++ -no-pie   -O2 -I/myfiles/openwrt-6.x/staging_dir/host/include  -pipe   -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Wconditionally-supported -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -static-libstdc++ -static-libgcc " > checksum-options.tmp \
&& /myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc/../move-if-change checksum-options.tmp checksum-options
g++  -fno-PIE -c   -O2 -I/myfiles/openwrt-6.x/staging_dir/host/include  -pipe   -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Wconditionally-supported -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings  -Wno-unused -DHAVE_CONFIG_H -I. -I. -I/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc -I/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc/. -I/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc/../include  -I/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc/../libcpp/include -I/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc/../libcody -I/myfiles/openwrt-6.x/staging_dir/host/include -I/myfiles/openwrt-6.x/staging_dir/host/include -I/myfiles/openwrt-6.x/staging_dir/host/include  -I/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc/../libdecnumber -I/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc/../libdecnumber/dpd -I../libdecnumber -I/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0/gcc/../libbacktrace   -o gimple-match.o -MT gimple-match.o -MMD -MP -MF ./.deps/gimple-match.TPo gimple-match.cc
{standard input}: Assembler messages:
{standard input}:202998: Warning: end of file not at end of a line; newline inserted
{standard input}:204166: Error: unbalanced parenthesis in operand 1.
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[5]: *** [Makefile:1158: gimple-match.o] Error 1
make[5]: Leaving directory '/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0-initial/gcc'
make[4]: *** [Makefile:4605: all-gcc] Error 2
make[4]: Leaving directory '/myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0-initial'
make[3]: *** [Makefile:29: /myfiles/openwrt-6.x/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gcc-13.3.0-initial/.built] Error 2
make[3]: Leaving directory '/myfiles/openwrt-6.x/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#328.91#51.58#401.93
    ERROR: toolchain/gcc/initial failed to build.
make[2]: *** [toolchain/Makefile:93: toolchain/gcc/initial/compile] Error 1
make[2]: Leaving directory '/myfiles/openwrt-6.x'
make[1]: *** [toolchain/Makefile:89: /myfiles/openwrt-6.x/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/myfiles/openwrt-6.x'
make: *** [/myfiles/openwrt-6.x/include/toplevel.mk:248: world] Error 2

**Comment by King-Of-Knights** [comment]
@xingpo5800 看起来是内存不够，https://github.com/MagicStack/uvloop/issues/340#issuecomment-719993413

**Comment by xingpo5800** [comment]
> @xingpo5800 看起来是内存不够，[MagicStack/uvloop#340 (comment)](https://github.com/MagicStack/uvloop/issues/340#issuecomment-719993413)
谢谢你的指点，确实是内存不足的问题，现在已经编译出来了，编译出来的固件libwrt-qualcommx-ipq60xx-qihoo_v6-squshfs-factory.ubi,还有一个sysupgrade.bin等文件,但是编译出来的固件我的qihoo v6无法安装，原系统是qsdk openwrt，在uboot刷完后启动不了，由于没有ttl我无法贴上日志，web上传刷机交验无效不给刷，这种情况是什么引起的？若您有时间，望请赐教，谢谢！

**Comment by King-Of-Knights** [comment]
> web上传刷机交验无效不给刷

能不能强行刷呢？

**Comment by xingpo5800** [comment]
> > web上传刷机交验无效不给刷灯
> 
> 能不能强行刷呢？

mtd -r write xxxx.bin "rootfs"强行刷后直接就进不了系统了，刷完直接断线，而且看路由器绿灯常亮，好像是断线后没重启，断电后不能完全启动进系统！.ubi和.bin都强刷过

**Comment by King-Of-Knights** [comment]
我手上没有这个机器，不方便测试这个问题，你加[群](https://qm.qq.com/q/dBUruGbvAA)吧，应该有人知道
