### ISSUE TITLE
luci-proto-relay和openclash冲突无法联网

### ISSUE THREAD

**Issue by SeamusCheng** [King-Of-Knights/openwrt-6.x#2]
JDC-AX1800PRO开启luci-proto-relay桥接后WiFi能正常连接上网，lan口电脑无法获取IP，同时开启luci-proto-relay桥接和openclash后WiFi无法连接网络。请大佬进行查验，感谢。

**Comment by King-Of-Knights** [comment]
这个问题应该和本项目无关，看看是不是开了tun，mwan3也可能有影响
