### ISSUE TITLE
drivers/net/dsa/mt7530.c:2411:36 编译报错 error: implicit declaration of function 'MT7530_PMCR_P'

### ISSUE THREAD

**Issue by lsgxeva** [King-Of-Knights/openwrt-6.x#8]
编译目标 nanopi r5s 时 ， drivers/net/dsa/mt7530.c:2411:36 编译报错。
需要将 MT7530_PMCR_P 重命名为 MT753X_PMCR_P ; MT7531_FORCE_LNK 重命名为 MT7531_FORCE_MODE_LNK
```
drivers/net/dsa/mt7530.c: In function 'mt7530_setup':
drivers/net/dsa/mt7530.c:2411:36: error: implicit declaration of function 'MT7530_PMCR_P'; did you mean 'MT7530_PCR_P'? [-Werror=implicit-function-declaration]
 2411 |                 mt7530_write(priv, MT7530_PMCR_P(i), MT7531_FORCE_LNK);
      |                                    ^~~~~~~~~~~~~
      |                                    MT7530_PCR_P
drivers/net/dsa/mt7530.c:2411:54: error: 'MT7531_FORCE_LNK' undeclared (first use in this function); did you mean 'MT7531_FORCE_MODE_LNK'?
 2411 |                 mt7530_write(priv, MT7530_PMCR_P(i), MT7531_FORCE_LNK);
      |                                                      ^~~~~~~~~~~~~~~~
      |                                                      MT7531_FORCE_MODE_LNK
drivers/net/dsa/mt7530.c:2411:54: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by King-Of-Knights** [comment]
请问你用的是什么机型？

**Comment by lsgxeva** [comment]
这个和机型无关，我选了好几个 都是这样的。 
例如 GL-AXT1800 也是这样的。 Nanopi-R5S  gl-ar300m16 都一样。
在 build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.6.41/drivers/net/dsa/mt7530.c 的 2411 行 ，是有问题的，会导致编译失败。

**Comment by King-Of-Knights** [comment]
看起来是Linux内核问题，是某个包带来的影响吗？

**Comment by lsgxeva** [comment]
我看 https://github.com/torvalds/linux/blob/master/drivers/net/dsa/mt7530.c 是正常的。
没有 2411行 这个内容 mt7530_write(priv, MT7530_PMCR_P(i), MT7531_FORCE_LNK);

**Comment by King-Of-Knights** [comment]
@lsgxeva 我的项目里似乎包括了修复这个问题的[补丁](https://github.com/King-Of-Knights/openwrt-6.x/blob/main/target/linux/generic/backport-6.6/790-39-v6.10-net-dsa-mt7530-refactor-MT7530_PMCR_P.patch#L72)，看看`make target/linux/{clean,prepare} V=s`输出的编译日志里面，有没有打上这个补丁？

**Comment by lsgxeva** [comment]
在尝试你提供的指令之前，我先 移除了 我自己 加的 补丁。
发现 mt7530.c 的 2411行 仍是错误的。
```
~/Develop/libwrt-mod$ sed -n '2411p' ./build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.6.41/drivers/net/dsa/mt7530.c 
		mt7530_write(priv, MT7530_PMCR_P(i), MT7531_FORCE_LNK);
/Develop/libwrt-mod$ 
```

**Comment by lsgxeva** [comment]
[log.txt](https://github.com/user-attachments/files/16344199/log.txt)
这个是执行命令后的日志文件

**Comment by lsgxeva** [comment]
我认为是 这个补丁 没 重构完整，漏掉了2411行的内容，导致没有替换完整。
target/linux/generic/backport-6.6/790-39-v6.10-net-dsa-mt7530-refactor-MT7530_PMCR_P.patch

**Comment by King-Of-Knights** [comment]
@lsgxeva 可否发个PR呢？

**Comment by lsgxeva** [comment]
好的，已经创建PR 。 原因是 pending-6.6 mt7530: fixed pending-6.6 723-net-mt7531-ensure-all-MACs-are-powered-down-before-r.patch 补丁导致的。
重命名 MT7530_PMCR_P 到 MT753X_PMCR_P 即可。
